edition = "2021"
format_strings = true
hex_literal_case = "Lower"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
